[package]
name = "testing"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[dev-dependencies]
quine-mc_cluskey = { path = "..", features = ["quickcheck"] }
quickcheck = "0.3.1"
skeptic = "0.4"

[build-dependencies]
skeptic = "0.4"
